const fs = require('fs');
const path = require('path');

const files = {
  'src/app/page.tsx': `
"use client";
import { useEffect, useState } from "react";
import { AnimatePresence } from "motion/react";
import AppLoader from "@/components/AppLoader";
import SiteHeader from "@/components/SiteHeader";
import ControlPanel from "@/components/ControlPanel";
import MapShell from "@/components/MapShell";
import JournalSection from "@/components/JournalSection";
import Footer from "@/components/Footer";
import Toast from "@/components/Toast";
import { useVoyageStore } from "@/lib/store";
export default function Home() {
  const [ready, setReady] = useState(false);
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      const tag = (document.activeElement?.tagName ?? "").toLowerCase();
      const st = useVoyageStore.getState();
      if (tag === "input" || tag === "textarea" || tag === "select") { if (e.key === "Escape") (document.activeElement as HTMLElement)?.blur(); return; }
      if (e.key === "/") { e.preventDefault(); document.getElementById("countrySearch")?.focus(); }
      else if (e.key === "Escape") st.closeDiscovery();
      else if (e.key === "ArrowLeft") st.prevMedia();
      else if (e.key === "ArrowRight") st.nextMedia();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, []);
  return (
    <>
      <AnimatePresence>{!ready && <AppLoader onReady={() => setReady(true)} />}</AnimatePresence>
      <div id="appShell" className={ready ? "ready" : ""}>
        <SiteHeader /><main className="main-wrap"><ControlPanel /><MapShell /><JournalSection /></main><Footer />
      </div>
      <Toast />
    </>
  );
}
`,
  'src/lib/config.ts': `
export const CONFIG = { GEOJSON_URL: "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson", GEOJSON_FALLBACK_URL: "https://cdn.jsdelivr.net/gh/nvkelso/natural-earth-vector@master/geojson/ne_110m_admin_0_countries.geojson", API_BASE: "https://media-api.markmykevin.workers.dev", MAP_CENTER: [20, 0] as [number, number], INITIAL_ZOOM: 2, MIN_ZOOM: 1, MAX_ZOOM: 6, SHIP_SPEED: 7000, JOURNAL_LIMIT: 8, COUNTRY_MEDIA_LIMIT: 8 };
export const COUNTRY_API_ALIASES: Record<string, string> = { "United States of America": "United States", "Russian Federation": "Russia", "Viet Nam": "Vietnam", "Türkiye": "Turkey", "Czechia": "Czech Republic", "Korea, Republic of": "South Korea" };
`,
  'src/lib/api.ts': `
import { CONFIG, COUNTRY_API_ALIASES } from "./config";
export type CountryMedia = { url: string; title: string; description: string; type: "image" | "video" };
function extractArray(p: any): any[] { if (Array.isArray(p)) return p; return Array.isArray(p?.data) ? p.data : Array.isArray(p?.results) ? p.results : Array.isArray(p?.items) ? p.items : []; }
function inferType(item: any, req: "image" | "video"): "image" | "video" { const raw = String(item?.type || item?.mimeType || "").toLowerCase(); if (/video|mp4|webm|mov/.test(raw)) return "video"; if (/image|jpg|jpeg|png|webp|gif/.test(raw)) return "image"; const url = String(item?.url || item?.src || "").toLowerCase(); return /\\.(mp4|webm|mov|m4v|avi)(\\?|$)/i.test(url) ? "video" : req; }
function normalize(item: any, req: "image" | "video"): CountryMedia | null { const url = item?.url || item?.downloadUrl || item?.src || item?.mediaUrl; if (!url) return null; return { url, title: item?.title || item?.name || "Untitled", description: item?.description || "", type: inferType(item, req) }; }
async function get(endpoint: string, params: URLSearchParams): Promise<CountryMedia[]> { const res = await fetch(CONFIG.API_BASE + endpoint + "?" + params, { cache: "no-store" }); if (!res.ok) throw new Error("API " + res.status); return extractArray(await res.json()).map((i) => normalize(i, endpoint.includes("video") ? "video" : "image")).filter((m): m is CountryMedia => !!m); }
export const fetchCountryMedia = (type: "image" | "video", country: string) => get(type === "video" ? "/api/videos/random" : "/api/images/random", new URLSearchParams({ limit: String(CONFIG.COUNTRY_MEDIA_LIMIT), country: COUNTRY_API_ALIASES[country] || country }));
export const fetchJournalMedia = (type: "image" | "video") => get(type === "video" ? "/api/videos/random" : "/api/images/random", new URLSearchParams({ limit: String(CONFIG.JOURNAL_LIMIT) }));
export function removeDuplicates(items: CountryMedia[]) { const seen = new Set<string>(); return items.filter((m) => (seen.has(m.url) ? false : (seen.add(m.url), true))); }
`,
  'src/lib/store.ts': `
import { create } from "zustand";
export type CountryMedia = { url: string; title: string; description: string; type: "image" | "video" };
let toastTimer: ReturnType<typeof setTimeout> | null = null;
interface VoyageState { countriesCount: number; voyageCount: number; totalDistance: number; discoveryOpen: boolean; discoveryCountry: string; discoveryMedia: CountryMedia[]; discoveryIndex: number; discoveryLatLng: [number, number] | null; toast: string; toastVisible: boolean; setCountriesCount: (n: number) => void; incrementVoyage: (d: number) => void; resetVoyage: () => void; openDiscovery: (c: string, m: CountryMedia[], ll: [number, number]) => void; closeDiscovery: () => void; nextMedia: () => void; prevMedia: () => void; showToast: (msg: string, duration?: number) => void; }
export const useVoyageStore = create<VoyageState>((set) => ({
  countriesCount: 0, voyageCount: 0, totalDistance: 0, discoveryOpen: false, discoveryCountry: "", discoveryMedia: [], discoveryIndex: 0, discoveryLatLng: null, toast: "", toastVisible: false,
  setCountriesCount: (n) => set({ countriesCount: n }),
  incrementVoyage: (d) => set((s) => ({ voyageCount: s.voyageCount + 1, totalDistance: s.totalDistance + d })),
  resetVoyage: () => set({ voyageCount: 0, totalDistance: 0, discoveryOpen: false, discoveryMedia: [], discoveryIndex: 0 }),
  openDiscovery: (c, m, ll) => set({ discoveryOpen: true, discoveryCountry: c, discoveryMedia: m, discoveryIndex: 0, discoveryLatLng: ll }),
  closeDiscovery: () => set({ discoveryOpen: false, discoveryMedia: [], discoveryIndex: 0, discoveryLatLng: null }),
  nextMedia: () => set((s) => (s.discoveryMedia.length > 1 ? { discoveryIndex: (s.discoveryIndex + 1) % s.discoveryMedia.length } : s)),
  prevMedia: () => set((s) => (s.discoveryMedia.length > 1 ? { discoveryIndex: (s.discoveryIndex - 1 + s.discoveryMedia.length) % s.discoveryMedia.length } : s)),
  showToast: (msg, duration = 3500) => { if (toastTimer) clearTimeout(toastTimer); set({ toast: msg, toastVisible: true }); toastTimer = setTimeout(() => set({ toastVisible: false }), duration); },
}));
`,
  'src/lib/mapActions.ts': `
import L from "leaflet"; import { CONFIG } from "./config"; import { useVoyageStore } from "./store"; import { fetchCountryMedia, removeDuplicates } from "./api";
let worldMap: L.Map | null = null; let countriesLayer: L.GeoJSON | null = null; let selectedLayer: any = null; let shipMarker: L.Marker | null = null; let routeLine: L.Polyline | null = null; let destinationMarker: L.CircleMarker | null = null; let voyageAnimation: number | null = null; let countries: { feature: any; name: string }[] = [];
const toRad = (d: number) => (d * Math.PI) / 180; const toDeg = (r: number) => (r * 180) / Math.PI;
function haversine(a: L.LatLng, b: L.LatLng) { const R = 6371, dLat = toRad(b.lat - a.lat), dLon = toRad(b.lng - a.lng); const h = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(a.lat)) * Math.cos(toRad(b.lat)) * Math.sin(dLon / 2) ** 2; return 2 * R * Math.asin(Math.sqrt(h)); }
function greatCircle(start: L.LatLng, end: L.LatLng, t: number): L.LatLng { const lat1 = toRad(start.lat), lon1 = toRad(start.lng), lat2 = toRad(end.lat), lon2 = toRad(end.lng); const x1 = Math.cos(lat1) * Math.cos(lon1), y1 = Math.cos(lat1) * Math.sin(lon1), z1 = Math.sin(lat1); const x2 = Math.cos(lat2) * Math.cos(lon2), y2 = Math.cos(lat2) * Math.sin(lon2), z2 = Math.sin(lat2); const angle = Math.acos(Math.max(-1, Math.min(1, x1 * x2 + y1 * y2 + z1 * z2))); if (Math.abs(angle) < 1e-6) return L.latLng(start.lat + (end.lat - start.lat) * t, start.lng + (end.lng - start.lng) * t); const s = Math.sin(angle), a = Math.sin((1 - t) * angle) / s, b = Math.sin(t * angle) / s; const x = a * x1 + b * x2, y = a * y1 + b * y2, z = a * z1 + b * z2; return L.latLng(toDeg(Math.atan2(z, Math.sqrt(x * x + y * y))), toDeg(Math.atan2(y, x))); }
const baseStyle = () => ({ color: "#765124", weight: 1, opacity: 0.85, fillColor: "#c7a766", fillOpacity: 0.34 });
const hoverStyle = () => ({ color: "#ffe3a0", weight: 2, fillColor: "#dcb96e", fillOpacity: 0.58 });
const selectStyle = () => ({ color: "#6ee9ff", weight: 2.5, fillColor: "#3d8f99", fillOpacity: 0.55, dashArray: "5 4" });
function shipIcon() { return L.divIcon({ className: "ancient-ship-marker", iconSize: [82, 82], iconAnchor: [41, 41], html: '<div style="position:relative;width:82px;height:82px;transform:translate(-50%,-50%);pointer-events:none;"><div style="position:absolute;left:9px;right:9px;bottom:20px;height:17px;background:linear-gradient(#75411e,#2e1609);border:2px solid #d2a153;border-radius:0 0 50% 50%;box-shadow:0 3px 5px rgba(0,0,0,.55);"></div><div style="position:absolute;left:39px;bottom:32px;width:4px;height:38px;background:#6e431d;box-shadow:1px 0 0 #d1a154;"></div><div style="position:absolute;left:22px;bottom:46px;width:37px;height:25px;background:linear-gradient(145deg,#ead294,#a87434);clip-path:polygon(50% 0,100% 100%,0 100%);border:1px solid #684018;transform-origin:bottom center;animation:shipSail 2.8s ease-in-out infinite;"></div><div style="position:absolute;left:42px;top:8px;width:17px;height:10px;background:#a63325;clip-path:polygon(0 0,100% 20%,75% 80%,0 100%);"></div><div style="position:absolute;left:4px;right:4px;bottom:11px;height:8px;background:radial-gradient(ellipse,rgba(190,230,231,.65),transparent 70%);animation:wakePulse 1.5s ease-in-out infinite;"></div></div>' }); }
async function openDiscovery(name: string, latlng: L.LatLng) { const st = useVoyageStore.getState(); st.openDiscovery(name, [], [latlng.lat, latlng.lng]); try { const [img, vid] = await Promise.allSettled([fetchCountryMedia("image", name), fetchCountryMedia("video", name)]); const media = removeDuplicates([...(img.status === "fulfilled" ? img.value : []), ...(vid.status === "fulfilled" ? vid.value : [])]); if (useVoyageStore.getState().discoveryCountry === name) useVoyageStore.setState({ discoveryMedia: media, discoveryIndex: 0 }); } catch { st.showToast("Archive error"); } }
function selectCountry(name: string, layer: any, latlng: L.LatLng) { if (selectedLayer) selectedLayer.setStyle(baseStyle()); selectedLayer = layer; layer.setStyle(selectStyle()); worldMap?.flyTo(latlng, Math.max(worldMap.getZoom(), 3), { duration: 1.1 }); openDiscovery(name, latlng); startVoyage(latlng); }
function startVoyage(end: L.LatLng) { if (!worldMap || !shipMarker) return; const start = shipMarker.getLatLng(); if (voyageAnimation) cancelAnimationFrame(voyageAnimation); routeLine?.remove(); destinationMarker?.remove(); const distance = haversine(start, end); if (distance < 1) return; useVoyageStore.getState().incrementVoyage(distance); routeLine = L.polyline([], { color: "#62e9ff", weight: 2, opacity: 0.82, dashArray: "7 9" }).addTo(worldMap); destinationMarker = L.circleMarker(end, { radius: 7, color: "#ffe29b", weight: 2, fillColor: "#5de5ff", fillOpacity: 0.75 }).addTo(worldMap); const startedAt = performance.now(); const duration = Math.min(CONFIG.SHIP_SPEED, Math.max(2500, distance * 3.5)); const animate = (now: number) => { const raw = Math.min((now - startedAt) / duration, 1); const t = raw < 0.5 ? 2 * raw * raw : 1 - Math.pow(-2 * raw + 2, 2) / 2; shipMarker?.setLatLng(greatCircle(start, end, t)); const pts: L.LatLng[] = []; const seg = Math.max(2, Math.ceil(t * 80)); for (let i = 0; i <= seg; i++) pts.push(greatCircle(start, end, t * (i / seg))); routeLine?.setLatLngs(pts); if (raw < 1) voyageAnimation = requestAnimationFrame(animate); else { voyageAnimation = null; destinationMarker?.setStyle({ radius: 9, fillOpacity: 0.95 }); } }; voyageAnimation = requestAnimationFrame(animate); }
export const mapActions = {
  initMap(el: HTMLElement) { if (worldMap) return; worldMap = L.map(el, { center: CONFIG.MAP_CENTER, zoom: CONFIG.INITIAL_ZOOM, minZoom: CONFIG.MIN_ZOOM, maxZoom: CONFIG.MAX_ZOOM, worldCopyJump: true }); L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", { maxZoom: 19, attribution: "&copy; OpenStreetMap contributors" }).addTo(worldMap); shipMarker = L.marker(CONFIG.MAP_CENTER, { icon: shipIcon(), zIndexOffset: 1000 }).addTo(worldMap); fetch(CONFIG.GEOJSON_URL).then((r) => r.json()).catch(() => fetch(CONFIG.GEOJSON_FALLBACK_URL).then((r) => r.json())).then((geojson) => { countries = geojson.features.map((f: any) => ({ feature: f, name: f.properties?.NAME || "Unknown Land" })).filter((c) => c.name !== "Unknown Land"); countriesLayer = L.geoJSON(geojson, { style: baseStyle, onEachFeature: (feature, layer: any) => { const name = feature.properties?.NAME || "Unknown Land"; layer.bindTooltip(name, { sticky: true, direction: "top", className: "country-tooltip" }); layer.on({ mouseover: () => selectedLayer !== layer && layer.setStyle(hoverStyle()), mouseout: () => selectedLayer !== layer && layer.setStyle(baseStyle()), click: (e: any) => selectCountry(name, layer, e.latlng) }); } }).addTo(worldMap!); useVoyageStore.getState().setCountriesCount(countries.length); }).catch(() => useVoyageStore.getState().showToast("Charts error", 7000)); setTimeout(() => worldMap?.invalidateSize(true), 150); },
  searchCountry(query: string) { const norm = query.normalize("NFD").replace(/[\\u0300-\\u036f]/g, "").toLowerCase().trim(); if (!norm) return; const st = useVoyageStore.getState(); if (!countries.length) return; const match = countries.find((c) => c.name.normalize("NFD").replace(/[\\u0300-\\u036f]/g, "").toLowerCase().includes(norm)); if (!match) return; const layer = countriesLayer?.getLayers().find((l: any) => l.feature === match.feature) as any; if (!layer) return; selectCountry(match.name, layer, L.geoJSON(match.feature).getBounds().getCenter()); },
  resetVoyage() { if (voyageAnimation) { cancelAnimationFrame(voyageAnimation); voyageAnimation = null; } routeLine?.remove(); routeLine = null; destinationMarker?.remove(); destinationMarker = null; selectedLayer?.setStyle(baseStyle()); selectedLayer = null; shipMarker?.setLatLng(CONFIG.MAP_CENTER); worldMap?.flyTo(CONFIG.MAP_CENTER, CONFIG.INITIAL_ZOOM, { duration: 1 }); useVoyageStore.getState().resetVoyage(); },
  positionDiscovery(el: HTMLElement, latlng: [number, number] | null) { if (!worldMap || !latlng) return; if (window.matchMedia("(max-width: 600px)").matches) return; const p = worldMap.latLngToContainerPoint(L.latLng(latlng[0], latlng[1])); const size = worldMap.getSize(); const w = el.offsetWidth, h = el.offsetHeight; let left = p.x + 18, top = p.y + 18; if (left + w > size.x - 12) left = p.x - w - 18; if (top + h > size.y - 12) top = p.y - h - 18; el.style.left = Math.max(8, Math.min(left, size.x - w - 8)) + "px"; el.style.top = Math.max(8, Math.min(top, size.y - h - 8)) + "px"; },
  onMapEvent(cb: () => void) { worldMap?.on("move zoom resize", cb); return () => worldMap?.off("move zoom resize", cb); },
};
`,
  'src/components/AppLoader.tsx': `"use client"; import { useEffect, useRef } from "react"; import { motion } from "motion/react"; import gsap from "gsap"; export default function AppLoader({ onReady }: { onReady: () => void }) { const barRef = useRef<HTMLDivElement>(null); useEffect(() => { const tl = gsap.timeline({ onComplete: onReady }); tl.to(barRef.current, { width: "100%", duration: 3, ease: "none" }); return () => { tl.kill(); }; }, [onReady]); return (<motion.div id="appLoader" exit={{ opacity: 0 }} transition={{ duration: 0.9 }}><div className="loader-parchment"><div className="loader-sigil"><div className="loader-ring" /><div className="loader-ring" /><div className="loader-ring" /><span className="loader-rune">✦</span><span className="loader-rune">✧</span><span className="loader-rune">✦</span><span className="loader-rune">✧</span><div className="loader-hourglass"><div className="loader-sand" /></div></div><h1 className="loader-title">The Great Voyage</h1><p className="loader-subtitle">Unfolding the mysteries...</p><div className="loader-progress"><div ref={barRef} className="loader-progress-bar" /></div><div className="loader-status">Consulting the old charts...</div></div></motion.div>); }`,
  'src/components/SiteHeader.tsx': `"use client"; import { motion } from "motion/react"; export default function SiteHeader() { return (<motion.header initial={{ y: -20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ duration: 0.8 }} className="site-header"><div className="brand"><div className="brand-compass" /><div><h1 className="brand-title">The Great Voyage</h1><p className="brand-subtitle">Chronicles of an Ancient Adventurer</p></div></div></motion.header>); }`,
  'src/components/ControlPanel.tsx': `"use client"; import { useRef } from "react"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { useVoyageStore } from "@/lib/store"; export default function ControlPanel() { const ref = useRef<HTMLInputElement>(null); const onKey = (e: React.KeyboardEvent<HTMLInputElement>) => { if (e.key === "Enter") import("@/lib/mapActions").then((m) => m.mapActions.searchCountry(ref.current?.value ?? "")); if (e.key === "Escape") { if (ref.current) ref.current.value = ""; useVoyageStore.getState().closeDiscovery(); } }; return (<section className="control-panel"><div className="search-wrap"><Input ref={ref} id="countrySearch" type="search" placeholder="Search..." className="search-input" onKeyDown={onKey} /></div><Button className="ancient-btn" onClick={() => import("@/lib/mapActions").then((m) => m.mapActions.resetVoyage())}>⟲ Reset Voyage</Button><Button className="ancient-btn" onClick={() => document.getElementById("journal")?.scrollIntoView({ behavior: "smooth", block: "start" })}>📜 Expedition Journal</Button></section>); }`,
  'src/components/LeafletMap.tsx': `"use client"; import { useEffect, useRef } from "react"; import { mapActions } from "@/lib/mapActions"; export default function LeafletMap() { const ref = useRef<HTMLDivElement>(null); useEffect(() => { if (ref.current) mapActions.initMap(ref.current); }, []); return <div ref={ref} id="map" className="map-canvas" />; }`,
  'src/components/CountryDiscovery.tsx': `"use client"; import { useEffect, useRef } from "react"; import { motion } from "motion/react"; import { useVoyageStore } from "@/lib/store"; import { mapActions } from "@/lib/mapActions"; export default function CountryDiscovery() { const ref = useRef<HTMLElement>(null); const { discoveryCountry, discoveryMedia, discoveryIndex, discoveryLatLng, closeDiscovery, nextMedia, prevMedia } = useVoyageStore(); const item = discoveryMedia[discoveryIndex]; useEffect(() => { const el = ref.current; if (!el) return; const place = () => mapActions.positionDiscovery(el, discoveryLatLng); place(); const off = mapActions.onMapEvent(place); window.addEventListener("resize", place); return () => { off(); window.removeEventListener("resize", place); }; }, [discoveryLatLng]); return (<motion.aside ref={ref} initial={{ opacity: 0, y: 10, scale: 0.96 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, scale: 0.96 }} transition={{ duration: 0.4 }} className="country-discovery"><div className="discovery-header"><h2 className="discovery-title">{discoveryCountry}</h2><button className="discovery-close" onClick={closeDiscovery}>×</button></div><div className="discovery-media-frame">{item ? (item.type === "video" ? <video src={item.url} controls playsInline /> : <img src={item.url} alt={item.title} />) : discoveryMedia.length === 0 ? (<div>✦ Summoning records ✦</div>) : (<div>No records found.</div>)}</div><div className="discovery-info"><h3>{item?.title ?? "Discovering..."}</h3><p>{item?.description || "Consulting..."}</p></div><div className="discovery-controls"><button onClick={prevMedia}>◀</button><button onClick={nextMedia}>▶</button></div></motion.aside>); }`,
  'src/components/MapShell.tsx': `"use client"; import dynamic from "next/dynamic"; import { AnimatePresence } from "motion/react"; import { useVoyageStore } from "@/lib/store"; import CountryDiscovery from "./CountryDiscovery"; const LeafletMap = dynamic(() => import("./LeafletMap"), { ssr: false }); export default function MapShell() { const countriesCount = useVoyageStore((s) => s.countriesCount); const voyageCount = useVoyageStore((s) => s.voyageCount); const totalDistance = useVoyageStore((s) => s.totalDistance); const discoveryOpen = useVoyageStore((s) => s.discoveryOpen); return (<section className="map-shell"><LeafletMap /><div className="map-hud"><div className="hud-card"><span className="hud-label">Lands Charted</span><span className="hud-value">{countriesCount.toLocaleString()}</span></div><div className="hud-card"><span className="hud-label">Voyages</span><span className="hud-value">{voyageCount.toLocaleString()}</span></div><div className="hud-card"><span className="hud-label">Distance</span><span className="hud-value">{Math.round(totalDistance).toLocaleString()} km</span></div></div><div className="map-compass"><div className="compass-outer" /><div className="compass-middle" /><div className="compass-inner" /><span className="compass-letter compass-n">N</span><span className="compass-letter compass-e">E</span><span className="compass-letter compass-s">S</span><span className="compass-letter compass-w">W</span></div><AnimatePresence>{discoveryOpen && <CountryDiscovery />}</AnimatePresence></section>); }`,
  'src/components/JournalCard.tsx': `"use client"; import { motion } from "motion/react"; import type { CountryMedia } from "@/lib/store"; const ROT = [-0.7, 0.55, -0.4, 0.8]; export default function JournalCard({ item, index }: { item: CountryMedia; index: number }) { const rot = ROT[index % 4]; return (<motion.article initial={{ opacity: 0, y: 35, rotate: rot, scale: 0.96 }} whileInView={{ opacity: 1, y: 0, rotate: rot, scale: 1 }} whileHover={{ y: -9, rotate: 0, scale: 1.015 }} viewport={{ once: true, margin: "-50px" }} transition={{ duration: 0.8, delay: (index % 4) * 0.07 }} className="journal-card"><div className="journal-frame"><div className="journal-frame-rune" /><div className="journal-media">{item.type === "video" ? <video controls playsInline src={item.url} /> : <img src={item.url} alt={item.title} />}</div></div><div className="journal-meta"><h3>{item.title}</h3><p>{item.description || "A fragment..."}</p><span className="journal-type">{item.type === "video" ? "MOVING RECORD" : "ILLUSTRATED RECORD"}</span></div></motion.article>); }`,
  'src/components/JournalSection.tsx': `"use client"; import { useEffect, useState } from "react"; import { fetchJournalMedia, removeDuplicates, type CountryMedia } from "@/lib/api"; import JournalCard from "./JournalCard"; export default function JournalSection() { const [media, setMedia] = useState<CountryMedia[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { (async () => { try { const [img, vid] = await Promise.allSettled([fetchJournalMedia("image"), fetchJournalMedia("video")]); setMedia(removeDuplicates([...(img.status === "fulfilled" ? img.value : []), ...(vid.status === "fulfilled" ? vid.value : [])])); } catch {} finally { setLoading(false); } })(); }, []); return (<section id="journal" className="journal-section"><div className="journal-heading"><h2>Expedition Journal</h2><p>Fragments, visions and records</p></div><div className="journal-grid">{loading ? (<div className="journal-empty"><strong>Opening archives...</strong></div>) : media.length === 0 ? (<div className="journal-empty"><strong>Archive unreachable.</strong></div>) : (media.slice(0, 8).map((m, i) => <JournalCard key={m.url + i} item={m} index={i} />))}</div></section>); }`,
  'src/components/Footer.tsx': `export default function Footer() { return (<footer className="site-footer"><span className="footer-rune">✦ ✧ ✦ ✧ ✦</span>The Great Voyage · Cartography of the Known World</footer>); }`,
  'src/components/Toast.tsx': `"use client"; import { useVoyageStore } from "@/lib/store"; export default function Toast() { const toast = useVoyageStore((s) => s.toast); const visible = useVoyageStore((s) => s.toastVisible); return <div id="toast" role="status" className={visible ? "show" : ""}>{toast}</div>; }`
};

for (const [filePath, content] of Object.entries(files)) {
  const fullPath = path.join(__dirname, filePath);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, content.trim() + '\n');
  console.log('Created:', filePath);
}
console.log('\n✅ All 15 files created successfully!');
